part of 'icon_data.dart';

// THIS FILE IS AUTOMATICALLY GENERATED!

/// [WarframeIcons] offers icons from Warframe fan kit converted to an icon font
class WarframeIcons {
  /// Warframe icons arbitrations [IconData] with Unicode 0xf101
  static const IconData arbitrations = WarframeIconData(0xf101);

  /// Warframe icons archwing [IconData] with Unicode 0xf102
  static const IconData archwing = WarframeIconData(0xf102);

  /// Warframe icons damageImpact [IconData] with Unicode 0xf103
  static const IconData damageImpact = WarframeIconData(0xf103);

  /// Warframe icons damagePuncture [IconData] with Unicode 0xf104
  static const IconData damagePuncture = WarframeIconData(0xf104);

  /// Warframe icons damageSlash [IconData] with Unicode 0xf105
  static const IconData damageSlash = WarframeIconData(0xf105);

  /// Warframe icons entrati [IconData] with Unicode 0xf106
  static const IconData entrati = WarframeIconData(0xf106);

  /// Warframe icons factionsCorpus [IconData] with Unicode 0xf107
  static const IconData factionsCorpus = WarframeIconData(0xf107);

  /// Warframe icons factionsCorrupted [IconData] with Unicode 0xf108
  static const IconData factionsCorrupted = WarframeIconData(0xf108);

  /// Warframe icons factionsGrineer [IconData] with Unicode 0xf109
  static const IconData factionsGrineer = WarframeIconData(0xf109);

  /// Warframe icons factionsInfested [IconData] with Unicode 0xf10a
  static const IconData factionsInfested = WarframeIconData(0xf10a);

  /// Warframe icons factionsMurmur [IconData] with Unicode 0xf10b
  static const IconData factionsMurmur = WarframeIconData(0xf10b);

  /// Warframe icons factionsNarmer [IconData] with Unicode 0xf10d
  static const IconData factionsNarmer = WarframeIconData(0xf10d);

  /// Warframe icons factionsSentient [IconData] with Unicode 0xf10e
  static const IconData factionsSentient = WarframeIconData(0xf10e);

  /// Warframe icons fissures1 [IconData] with Unicode 0xf10f
  static const IconData fissures1 = WarframeIconData(0xf10f);

  /// Warframe icons fissures2 [IconData] with Unicode 0xf110
  static const IconData fissures2 = WarframeIconData(0xf110);

  /// Warframe icons fissures3 [IconData] with Unicode 0xf111
  static const IconData fissures3 = WarframeIconData(0xf111);

  /// Warframe icons fissures4 [IconData] with Unicode 0xf112
  static const IconData fissures4 = WarframeIconData(0xf112);

  /// Warframe icons fissures5 [IconData] with Unicode 0xf113
  static const IconData fissures5 = WarframeIconData(0xf113);

  /// Warframe icons fissuresAxi [IconData] with Unicode 0xf114
  static const IconData fissuresAxi = WarframeIconData(0xf114);

  /// Warframe icons fissuresLith [IconData] with Unicode 0xf115
  static const IconData fissuresLith = WarframeIconData(0xf115);

  /// Warframe icons fissuresMeso [IconData] with Unicode 0xf116
  static const IconData fissuresMeso = WarframeIconData(0xf116);

  /// Warframe icons fissuresNeo [IconData] with Unicode 0xf117
  static const IconData fissuresNeo = WarframeIconData(0xf117);

  /// Warframe icons fissuresRequiem [IconData] with Unicode 0xf118
  static const IconData fissuresRequiem = WarframeIconData(0xf118);

  /// Warframe icons hexis [IconData] with Unicode 0xf119
  static const IconData hexis = WarframeIconData(0xf119);

  /// Warframe icons kuvaKuva [IconData] with Unicode 0xf11a
  static const IconData kuvaKuva = WarframeIconData(0xf11a);

  /// Warframe icons kuvaKuvaflood [IconData] with Unicode 0xf11b
  static const IconData kuvaKuvaflood = WarframeIconData(0xf11b);

  /// Warframe icons loading [IconData] with Unicode 0xf11c
  static const IconData loading = WarframeIconData(0xf11c);

  /// Warframe icons menuAll [IconData] with Unicode 0xf11d
  static const IconData menuAll = WarframeIconData(0xf11d);

  /// Warframe icons menuAmp [IconData] with Unicode 0xf11e
  static const IconData menuAmp = WarframeIconData(0xf11e);

  /// Warframe icons menuArcane [IconData] with Unicode 0xf11f
  static const IconData menuArcane = WarframeIconData(0xf11f);

  /// Warframe icons menuArchwing [IconData] with Unicode 0xf120
  static const IconData menuArchwing = WarframeIconData(0xf120);

  /// Warframe icons menuArchwingColour [IconData] with Unicode 0xf121
  static const IconData menuArchwingColour = WarframeIconData(0xf121);

  /// Warframe icons menuArchwingEmblem [IconData] with Unicode 0xf122
  static const IconData menuArchwingEmblem = WarframeIconData(0xf122);

  /// Warframe icons menuArchwingPrimary [IconData] with Unicode 0xf123
  static const IconData menuArchwingPrimary = WarframeIconData(0xf123);

  /// Warframe icons menuArchwingSecondary [IconData] with Unicode 0xf124
  static const IconData menuArchwingSecondary = WarframeIconData(0xf124);

  /// Warframe icons menuArmor [IconData] with Unicode 0xf125
  static const IconData menuArmor = WarframeIconData(0xf125);

  /// Warframe icons menuAugment [IconData] with Unicode 0xf126
  static const IconData menuAugment = WarframeIconData(0xf126);

  /// Warframe icons menuAura [IconData] with Unicode 0xf127
  static const IconData menuAura = WarframeIconData(0xf127);

  /// Warframe icons menuAvionics [IconData] with Unicode 0xf128
  static const IconData menuAvionics = WarframeIconData(0xf128);

  /// Warframe icons menuAvionicsDefensive [IconData] with Unicode 0xf129
  static const IconData menuAvionicsDefensive = WarframeIconData(0xf129);

  /// Warframe icons menuAvionicsOffensive [IconData] with Unicode 0xf12a
  static const IconData menuAvionicsOffensive = WarframeIconData(0xf12a);

  /// Warframe icons menuAvionicsSuper [IconData] with Unicode 0xf12b
  static const IconData menuAvionicsSuper = WarframeIconData(0xf12b);

  /// Warframe icons menuAvionicsTactical [IconData] with Unicode 0xf12c
  static const IconData menuAvionicsTactical = WarframeIconData(0xf12c);

  /// Warframe icons menuBarracks [IconData] with Unicode 0xf12d
  static const IconData menuBarracks = WarframeIconData(0xf12d);

  /// Warframe icons menuBile [IconData] with Unicode 0xf12e
  static const IconData menuBile = WarframeIconData(0xf12e);

  /// Warframe icons menuBiotics [IconData] with Unicode 0xf12f
  static const IconData menuBiotics = WarframeIconData(0xf12f);

  /// Warframe icons menuBlueprint [IconData] with Unicode 0xf130
  static const IconData menuBlueprint = WarframeIconData(0xf130);

  /// Warframe icons menuBuild [IconData] with Unicode 0xf131
  static const IconData menuBuild = WarframeIconData(0xf131);

  /// Warframe icons menuCalx [IconData] with Unicode 0xf132
  static const IconData menuCalx = WarframeIconData(0xf132);

  /// Warframe icons menuCapacity [IconData] with Unicode 0xf133
  static const IconData menuCapacity = WarframeIconData(0xf133);

  /// Warframe icons menuCephalon [IconData] with Unicode 0xf134
  static const IconData menuCephalon = WarframeIconData(0xf134);

  /// Warframe icons menuCetusElder [IconData] with Unicode 0xf135
  static const IconData menuCetusElder = WarframeIconData(0xf135);

  /// Warframe icons menuChangeSkins [IconData] with Unicode 0xf136
  static const IconData menuChangeSkins = WarframeIconData(0xf136);

  /// Warframe icons menuClanObstacleCourse [IconData] with Unicode 0xf137
  static const IconData menuClanObstacleCourse = WarframeIconData(0xf137);

  /// Warframe icons menuCommand [IconData] with Unicode 0xf138
  static const IconData menuCommand = WarframeIconData(0xf138);

  /// Warframe icons menuConnector [IconData] with Unicode 0xf139
  static const IconData menuConnector = WarframeIconData(0xf139);

  /// Warframe icons menuCorpus [IconData] with Unicode 0xf13a
  static const IconData menuCorpus = WarframeIconData(0xf13a);

  /// Warframe icons menuCraftingAmpBrace [IconData] with Unicode 0xf13b
  static const IconData menuCraftingAmpBrace = WarframeIconData(0xf13b);

  /// Warframe icons menuCraftingAmpPrism [IconData] with Unicode 0xf13c
  static const IconData menuCraftingAmpPrism = WarframeIconData(0xf13c);

  /// Warframe icons menuCraftingAmpScaffold [IconData] with Unicode 0xf13d
  static const IconData menuCraftingAmpScaffold = WarframeIconData(0xf13d);

  /// Warframe icons menuCraftingHoundBody [IconData] with Unicode 0xf13e
  static const IconData menuCraftingHoundBody = WarframeIconData(0xf13e);

  /// Warframe icons menuCraftingHoundHead [IconData] with Unicode 0xf13f
  static const IconData menuCraftingHoundHead = WarframeIconData(0xf13f);

  /// Warframe icons menuCraftingHoundLegs [IconData] with Unicode 0xf140
  static const IconData menuCraftingHoundLegs = WarframeIconData(0xf140);

  /// Warframe icons menuCraftingHoundTail [IconData] with Unicode 0xf141
  static const IconData menuCraftingHoundTail = WarframeIconData(0xf141);

  /// Warframe icons menuCraftingKDriveBoard [IconData] with Unicode 0xf142
  static const IconData menuCraftingKDriveBoard = WarframeIconData(0xf142);

  /// Warframe icons menuCraftingKDriveJet [IconData] with Unicode 0xf143
  static const IconData menuCraftingKDriveJet = WarframeIconData(0xf143);

  /// Warframe icons menuCraftingKDriveNose [IconData] with Unicode 0xf144
  static const IconData menuCraftingKDriveNose = WarframeIconData(0xf144);

  /// Warframe icons menuCraftingKDriveReactor [IconData] with Unicode 0xf145
  static const IconData menuCraftingKDriveReactor = WarframeIconData(0xf145);

  /// Warframe icons menuCraftingKitgunChamber [IconData] with Unicode 0xf146
  static const IconData menuCraftingKitgunChamber = WarframeIconData(0xf146);

  /// Warframe icons menuCraftingKitgunGrip [IconData] with Unicode 0xf147
  static const IconData menuCraftingKitgunGrip = WarframeIconData(0xf147);

  /// Warframe icons menuCraftingKitgunLoader [IconData] with Unicode 0xf148
  static const IconData menuCraftingKitgunLoader = WarframeIconData(0xf148);

  /// Warframe icons menuCraftingKitgunPrimaryGrip [IconData] with Unicode 0xf149
  static const IconData menuCraftingKitgunPrimaryGrip = WarframeIconData(0xf149);

  /// Warframe icons menuCraftingMoaBrackets [IconData] with Unicode 0xf14a
  static const IconData menuCraftingMoaBrackets = WarframeIconData(0xf14a);

  /// Warframe icons menuCraftingMoaCore [IconData] with Unicode 0xf14b
  static const IconData menuCraftingMoaCore = WarframeIconData(0xf14b);

  /// Warframe icons menuCraftingMoaGyro [IconData] with Unicode 0xf14c
  static const IconData menuCraftingMoaGyro = WarframeIconData(0xf14c);

  /// Warframe icons menuCraftingMoaModel [IconData] with Unicode 0xf14d
  static const IconData menuCraftingMoaModel = WarframeIconData(0xf14d);

  /// Warframe icons menuDisplays [IconData] with Unicode 0xf14e
  static const IconData menuDisplays = WarframeIconData(0xf14e);

  /// Warframe icons menuDrone [IconData] with Unicode 0xf14f
  static const IconData menuDrone = WarframeIconData(0xf14f);

  /// Warframe icons menuDuplicate [IconData] with Unicode 0xf150
  static const IconData menuDuplicate = WarframeIconData(0xf150);

  /// Warframe icons menuEmotes [IconData] with Unicode 0xf151
  static const IconData menuEmotes = WarframeIconData(0xf151);

  /// Warframe icons menuEnergy [IconData] with Unicode 0xf152
  static const IconData menuEnergy = WarframeIconData(0xf152);

  /// Warframe icons menuEngineering [IconData] with Unicode 0xf153
  static const IconData menuEngineering = WarframeIconData(0xf153);

  /// Warframe icons menuEntrati [IconData] with Unicode 0xf154
  static const IconData menuEntrati = WarframeIconData(0xf154);

  /// Warframe icons menuEquip [IconData] with Unicode 0xf155
  static const IconData menuEquip = WarframeIconData(0xf155);

  /// Warframe icons menuExilus [IconData] with Unicode 0xf156
  static const IconData menuExilus = WarframeIconData(0xf156);

  /// Warframe icons menuFavorite [IconData] with Unicode 0xf157
  static const IconData menuFavorite = WarframeIconData(0xf157);

  /// Warframe icons menuFishLarge [IconData] with Unicode 0xf158
  static const IconData menuFishLarge = WarframeIconData(0xf158);

  /// Warframe icons menuFishMedium [IconData] with Unicode 0xf159
  static const IconData menuFishMedium = WarframeIconData(0xf159);

  /// Warframe icons menuFishSmall [IconData] with Unicode 0xf15a
  static const IconData menuFishSmall = WarframeIconData(0xf15a);

  /// Warframe icons menuFusion [IconData] with Unicode 0xf15b
  static const IconData menuFusion = WarframeIconData(0xf15b);

  /// Warframe icons menuFx [IconData] with Unicode 0xf15c
  static const IconData menuFx = WarframeIconData(0xf15c);

  /// Warframe icons menuGara [IconData] with Unicode 0xf15d
  static const IconData menuGara = WarframeIconData(0xf15d);

  /// Warframe icons menuGarden [IconData] with Unicode 0xf15e
  static const IconData menuGarden = WarframeIconData(0xf15e);

  /// Warframe icons menuGear [IconData] with Unicode 0xf15f
  static const IconData menuGear = WarframeIconData(0xf15f);

  /// Warframe icons menuGearWheel [IconData] with Unicode 0xf160
  static const IconData menuGearWheel = WarframeIconData(0xf160);

  /// Warframe icons menuGeneticImprint [IconData] with Unicode 0xf161
  static const IconData menuGeneticImprint = WarframeIconData(0xf161);

  /// Warframe icons menuGhouls [IconData] with Unicode 0xf162
  static const IconData menuGhouls = WarframeIconData(0xf162);

  /// Warframe icons menuGift [IconData] with Unicode 0xf163
  static const IconData menuGift = WarframeIconData(0xf163);

  /// Warframe icons menuGlyph [IconData] with Unicode 0xf164
  static const IconData menuGlyph = WarframeIconData(0xf164);

  /// Warframe icons menuGrineer [IconData] with Unicode 0xf165
  static const IconData menuGrineer = WarframeIconData(0xf165);

  /// Warframe icons menuGrip [IconData] with Unicode 0xf166
  static const IconData menuGrip = WarframeIconData(0xf166);

  /// Warframe icons menuGunnery [IconData] with Unicode 0xf167
  static const IconData menuGunnery = WarframeIconData(0xf167);

  /// Warframe icons menuHall [IconData] with Unicode 0xf168
  static const IconData menuHall = WarframeIconData(0xf168);

  /// Warframe icons menuIncomplete [IconData] with Unicode 0xf169
  static const IconData menuIncomplete = WarframeIconData(0xf169);

  /// Warframe icons menuIndividualObstacleCourse [IconData] with Unicode 0xf16a
  static const IconData menuIndividualObstacleCourse = WarframeIconData(0xf16a);

  /// Warframe icons menuInfested [IconData] with Unicode 0xf16b
  static const IconData menuInfested = WarframeIconData(0xf16b);

  /// Warframe icons menuKavat [IconData] with Unicode 0xf16c
  static const IconData menuKavat = WarframeIconData(0xf16c);

  /// Warframe icons menuKeys [IconData] with Unicode 0xf16d
  static const IconData menuKeys = WarframeIconData(0xf16d);

  /// Warframe icons menuKubrow [IconData] with Unicode 0xf16e
  static const IconData menuKubrow = WarframeIconData(0xf16e);

  /// Warframe icons menuKuvaLichActive [IconData] with Unicode 0xf16f
  static const IconData menuKuvaLichActive = WarframeIconData(0xf16f);

  /// Warframe icons menuKuvaLichConverted [IconData] with Unicode 0xf170
  static const IconData menuKuvaLichConverted = WarframeIconData(0xf170);

  /// Warframe icons menuKuvaLichTraded [IconData] with Unicode 0xf171
  static const IconData menuKuvaLichTraded = WarframeIconData(0xf171);

  /// Warframe icons menuKuvaLichVanquished [IconData] with Unicode 0xf172
  static const IconData menuKuvaLichVanquished = WarframeIconData(0xf172);

  /// Warframe icons menuLab [IconData] with Unicode 0xf173
  static const IconData menuLab = WarframeIconData(0xf173);

  /// Warframe icons menuLichCategory [IconData] with Unicode 0xf174
  static const IconData menuLichCategory = WarframeIconData(0xf174);

  /// Warframe icons menuLimitedTime [IconData] with Unicode 0xf175
  static const IconData menuLimitedTime = WarframeIconData(0xf175);

  /// Warframe icons menuLink [IconData] with Unicode 0xf176
  static const IconData menuLink = WarframeIconData(0xf176);

  /// Warframe icons menuLotusEmblem [IconData] with Unicode 0xf177
  static const IconData menuLotusEmblem = WarframeIconData(0xf177);

  /// Warframe icons menuManufacturerLavan [IconData] with Unicode 0xf178
  static const IconData menuManufacturerLavan = WarframeIconData(0xf178);

  /// Warframe icons menuManufacturerSigma [IconData] with Unicode 0xf179
  static const IconData menuManufacturerSigma = WarframeIconData(0xf179);

  /// Warframe icons menuManufacturerVidar [IconData] with Unicode 0xf17a
  static const IconData menuManufacturerVidar = WarframeIconData(0xf17a);

  /// Warframe icons menuManufacturerZekti [IconData] with Unicode 0xf17b
  static const IconData menuManufacturerZekti = WarframeIconData(0xf17b);

  /// Warframe icons menuMaterials [IconData] with Unicode 0xf17c
  static const IconData menuMaterials = WarframeIconData(0xf17c);

  /// Warframe icons menuMaterialsOff [IconData] with Unicode 0xf17d
  static const IconData menuMaterialsOff = WarframeIconData(0xf17d);

  /// Warframe icons menuMech [IconData] with Unicode 0xf17e
  static const IconData menuMech = WarframeIconData(0xf17e);

  /// Warframe icons menuMechBoard [IconData] with Unicode 0xf17f
  static const IconData menuMechBoard = WarframeIconData(0xf17f);

  /// Warframe icons menuMelee [IconData] with Unicode 0xf180
  static const IconData menuMelee = WarframeIconData(0xf180);

  /// Warframe icons menuMisc [IconData] with Unicode 0xf181
  static const IconData menuMisc = WarframeIconData(0xf181);

  /// Warframe icons menuMkI [IconData] with Unicode 0xf182
  static const IconData menuMkI = WarframeIconData(0xf182);

  /// Warframe icons menuMkII [IconData] with Unicode 0xf183
  static const IconData menuMkII = WarframeIconData(0xf183);

  /// Warframe icons menuMkIII [IconData] with Unicode 0xf184
  static const IconData menuMkIII = WarframeIconData(0xf184);

  /// Warframe icons menuMods [IconData] with Unicode 0xf185
  static const IconData menuMods = WarframeIconData(0xf185);

  /// Warframe icons menuModularItem [IconData] with Unicode 0xf186
  static const IconData menuModularItem = WarframeIconData(0xf186);

  /// Warframe icons menuNatural [IconData] with Unicode 0xf187
  static const IconData menuNatural = WarframeIconData(0xf187);

  /// Warframe icons menuNoggles [IconData] with Unicode 0xf188
  static const IconData menuNoggles = WarframeIconData(0xf188);

  /// Warframe icons menuOperator [IconData] with Unicode 0xf189
  static const IconData menuOperator = WarframeIconData(0xf189);

  /// Warframe icons menuOrokinOn [IconData] with Unicode 0xf18a
  static const IconData menuOrokinOn = WarframeIconData(0xf18a);

  /// Warframe icons menuOwnedBlueprint [IconData] with Unicode 0xf18b
  static const IconData menuOwnedBlueprint = WarframeIconData(0xf18b);

  /// Warframe icons menuOxides [IconData] with Unicode 0xf18c
  static const IconData menuOxides = WarframeIconData(0xf18c);

  /// Warframe icons menuParazon [IconData] with Unicode 0xf18d
  static const IconData menuParazon = WarframeIconData(0xf18d);

  /// Warframe icons menuParazonLong [IconData] with Unicode 0xf18e
  static const IconData menuParazonLong = WarframeIconData(0xf18e);

  /// Warframe icons menuParazonLongShadow [IconData] with Unicode 0xf18f
  static const IconData menuParazonLongShadow = WarframeIconData(0xf18f);

  /// Warframe icons menuParazonLongShadow2 [IconData] with Unicode 0xf190
  static const IconData menuParazonLongShadow2 = WarframeIconData(0xf190);

  /// Warframe icons menuPheromones [IconData] with Unicode 0xf191
  static const IconData menuPheromones = WarframeIconData(0xf191);

  /// Warframe icons menuPilot [IconData] with Unicode 0xf192
  static const IconData menuPilot = WarframeIconData(0xf192);

  /// Warframe icons menuPistol [IconData] with Unicode 0xf193
  static const IconData menuPistol = WarframeIconData(0xf193);

  /// Warframe icons menuPlayerShip [IconData] with Unicode 0xf194
  static const IconData menuPlayerShip = WarframeIconData(0xf194);

  /// Warframe icons menuPrexCategory [IconData] with Unicode 0xf195
  static const IconData menuPrexCategory = WarframeIconData(0xf195);

  /// Warframe icons menuPrimaryWeaponBow [IconData] with Unicode 0xf196
  static const IconData menuPrimaryWeaponBow = WarframeIconData(0xf196);

  /// Warframe icons menuPrimaryWeaponLauncher [IconData] with Unicode 0xf197
  static const IconData menuPrimaryWeaponLauncher = WarframeIconData(0xf197);

  /// Warframe icons menuPrimaryWeaponRifle [IconData] with Unicode 0xf198
  static const IconData menuPrimaryWeaponRifle = WarframeIconData(0xf198);

  /// Warframe icons menuPrimaryWeaponShotgun [IconData] with Unicode 0xf199
  static const IconData menuPrimaryWeaponShotgun = WarframeIconData(0xf199);

  /// Warframe icons menuPrimaryWeaponSniper [IconData] with Unicode 0xf19a
  static const IconData menuPrimaryWeaponSniper = WarframeIconData(0xf19a);

  /// Warframe icons menuPrimaryWeaponSpeargun [IconData] with Unicode 0xf19b
  static const IconData menuPrimaryWeaponSpeargun = WarframeIconData(0xf19b);

  /// Warframe icons menuPrimaryWeaponSpecial [IconData] with Unicode 0xf19c
  static const IconData menuPrimaryWeaponSpecial = WarframeIconData(0xf19c);

  /// Warframe icons menuPrimeParts [IconData] with Unicode 0xf19d
  static const IconData menuPrimeParts = WarframeIconData(0xf19d);

  /// Warframe icons menuProspector [IconData] with Unicode 0xf19e
  static const IconData menuProspector = WarframeIconData(0xf19e);

  /// Warframe icons menuPurchase [IconData] with Unicode 0xf19f
  static const IconData menuPurchase = WarframeIconData(0xf19f);

  /// Warframe icons menuQuestPickerActive [IconData] with Unicode 0xf1a0
  static const IconData menuQuestPickerActive = WarframeIconData(0xf1a0);

  /// Warframe icons menuQuestPickerCompleted [IconData] with Unicode 0xf1a1
  static const IconData menuQuestPickerCompleted = WarframeIconData(0xf1a1);

  /// Warframe icons menuQuestPickerMystery [IconData] with Unicode 0xf1a2
  static const IconData menuQuestPickerMystery = WarframeIconData(0xf1a2);

  /// Warframe icons menuRailjack [IconData] with Unicode 0xf1a3
  static const IconData menuRailjack = WarframeIconData(0xf1a3);

  /// Warframe icons menuRailjack2 [IconData] with Unicode 0xf1a4
  static const IconData menuRailjack2 = WarframeIconData(0xf1a4);

  /// Warframe icons menuRailjackAbilities [IconData] with Unicode 0xf1a5
  static const IconData menuRailjackAbilities = WarframeIconData(0xf1a5);

  /// Warframe icons menuRailjackCountermeasures [IconData] with Unicode 0xf1a6
  static const IconData menuRailjackCountermeasures = WarframeIconData(0xf1a6);

  /// Warframe icons menuRailjackOrdnance [IconData] with Unicode 0xf1a7
  static const IconData menuRailjackOrdnance = WarframeIconData(0xf1a7);

  /// Warframe icons menuRailjackPilot [IconData] with Unicode 0xf1a8
  static const IconData menuRailjackPilot = WarframeIconData(0xf1a8);

  /// Warframe icons menuRailjackTurrets [IconData] with Unicode 0xf1a9
  static const IconData menuRailjackTurrets = WarframeIconData(0xf1a9);

  /// Warframe icons menuRelatedItems [IconData] with Unicode 0xf1aa
  static const IconData menuRelatedItems = WarframeIconData(0xf1aa);

  /// Warframe icons menuRelic [IconData] with Unicode 0xf1ab
  static const IconData menuRelic = WarframeIconData(0xf1ab);

  /// Warframe icons menuRelicAxi [IconData] with Unicode 0xf1ac
  static const IconData menuRelicAxi = WarframeIconData(0xf1ac);

  /// Warframe icons menuRelicLith [IconData] with Unicode 0xf1ad
  static const IconData menuRelicLith = WarframeIconData(0xf1ad);

  /// Warframe icons menuRelicMeso [IconData] with Unicode 0xf1ae
  static const IconData menuRelicMeso = WarframeIconData(0xf1ae);

  /// Warframe icons menuRelicNeo [IconData] with Unicode 0xf1af
  static const IconData menuRelicNeo = WarframeIconData(0xf1af);

  /// Warframe icons menuRequiemMod [IconData] with Unicode 0xf1b0
  static const IconData menuRequiemMod = WarframeIconData(0xf1b0);

  /// Warframe icons menuRequiemRelic [IconData] with Unicode 0xf1b1
  static const IconData menuRequiemRelic = WarframeIconData(0xf1b1);

  /// Warframe icons menuRequirementsMet [IconData] with Unicode 0xf1b2
  static const IconData menuRequirementsMet = WarframeIconData(0xf1b2);

  /// Warframe icons menuResearchCorpus [IconData] with Unicode 0xf1b3
  static const IconData menuResearchCorpus = WarframeIconData(0xf1b3);

  /// Warframe icons menuResearchGrineer [IconData] with Unicode 0xf1b4
  static const IconData menuResearchGrineer = WarframeIconData(0xf1b4);

  /// Warframe icons menuResearchInfested [IconData] with Unicode 0xf1b5
  static const IconData menuResearchInfested = WarframeIconData(0xf1b5);

  /// Warframe icons menuResearchOrokin [IconData] with Unicode 0xf1b6
  static const IconData menuResearchOrokin = WarframeIconData(0xf1b6);

  /// Warframe icons menuResearchRailjack [IconData] with Unicode 0xf1b7
  static const IconData menuResearchRailjack = WarframeIconData(0xf1b7);

  /// Warframe icons menuResearchTenno [IconData] with Unicode 0xf1b8
  static const IconData menuResearchTenno = WarframeIconData(0xf1b8);

  /// Warframe icons menuResourceDrone [IconData] with Unicode 0xf1b9
  static const IconData menuResourceDrone = WarframeIconData(0xf1b9);

  /// Warframe icons menuRifle [IconData] with Unicode 0xf1ba
  static const IconData menuRifle = WarframeIconData(0xf1ba);

  /// Warframe icons menuRifleOff [IconData] with Unicode 0xf1bb
  static const IconData menuRifleOff = WarframeIconData(0xf1bb);

  /// Warframe icons menuRivenMod [IconData] with Unicode 0xf1bc
  static const IconData menuRivenMod = WarframeIconData(0xf1bc);

  /// Warframe icons menuRoundVial [IconData] with Unicode 0xf1bd
  static const IconData menuRoundVial = WarframeIconData(0xf1bd);

  /// Warframe icons menuSalvage [IconData] with Unicode 0xf1be
  static const IconData menuSalvage = WarframeIconData(0xf1be);

  /// Warframe icons menuSentinel [IconData] with Unicode 0xf1bf
  static const IconData menuSentinel = WarframeIconData(0xf1bf);

  /// Warframe icons menuShotgun [IconData] with Unicode 0xf1c0
  static const IconData menuShotgun = WarframeIconData(0xf1c0);

  /// Warframe icons menuSigils [IconData] with Unicode 0xf1c1
  static const IconData menuSigils = WarframeIconData(0xf1c1);

  /// Warframe icons menuSimaris [IconData] with Unicode 0xf1c2
  static const IconData menuSimaris = WarframeIconData(0xf1c2);

  /// Warframe icons menuSkins [IconData] with Unicode 0xf1c3
  static const IconData menuSkins = WarframeIconData(0xf1c3);

  /// Warframe icons menuSolaris [IconData] with Unicode 0xf1c4
  static const IconData menuSolaris = WarframeIconData(0xf1c4);

  /// Warframe icons menuSquareVial [IconData] with Unicode 0xf1c5
  static const IconData menuSquareVial = WarframeIconData(0xf1c5);

  /// Warframe icons menuStance [IconData] with Unicode 0xf1c6
  static const IconData menuStance = WarframeIconData(0xf1c6);

  /// Warframe icons menuStrike [IconData] with Unicode 0xf1c7
  static const IconData menuStrike = WarframeIconData(0xf1c7);

  /// Warframe icons menuSwatch [IconData] with Unicode 0xf1c8
  static const IconData menuSwatch = WarframeIconData(0xf1c8);

  /// Warframe icons menuSynthetics [IconData] with Unicode 0xf1c9
  static const IconData menuSynthetics = WarframeIconData(0xf1c9);

  /// Warframe icons menuSynthetics2 [IconData] with Unicode 0xf1ca
  static const IconData menuSynthetics2 = WarframeIconData(0xf1ca);

  /// Warframe icons menuTactical [IconData] with Unicode 0xf1cb
  static const IconData menuTactical = WarframeIconData(0xf1cb);

  /// Warframe icons menuTeleport [IconData] with Unicode 0xf1cc
  static const IconData menuTeleport = WarframeIconData(0xf1cc);

  /// Warframe icons menuTenets [IconData] with Unicode 0xf1cd
  static const IconData menuTenets = WarframeIconData(0xf1cd);

  /// Warframe icons menuUtility [IconData] with Unicode 0xf1ce
  static const IconData menuUtility = WarframeIconData(0xf1ce);

  /// Warframe icons menuUtility2 [IconData] with Unicode 0xf1cf
  static const IconData menuUtility2 = WarframeIconData(0xf1cf);

  /// Warframe icons menuVehiclesKdrive [IconData] with Unicode 0xf1d0
  static const IconData menuVehiclesKdrive = WarframeIconData(0xf1d0);

  /// Warframe icons menuWarframe [IconData] with Unicode 0xf1d1
  static const IconData menuWarframe = WarframeIconData(0xf1d1);

  /// Warframe icons menuWarframeOff [IconData] with Unicode 0xf1d2
  static const IconData menuWarframeOff = WarframeIconData(0xf1d2);

  /// Warframe icons menuWeapons [IconData] with Unicode 0xf1d3
  static const IconData menuWeapons = WarframeIconData(0xf1d3);

  /// Warframe icons menuWild [IconData] with Unicode 0xf1d4
  static const IconData menuWild = WarframeIconData(0xf1d4);

  /// Warframe icons menuWoundedInfestedCritter [IconData] with Unicode 0xf1d5
  static const IconData menuWoundedInfestedCritter = WarframeIconData(0xf1d5);

  /// Warframe icons menuWoundedInfestedPredator [IconData] with Unicode 0xf1d6
  static const IconData menuWoundedInfestedPredator = WarframeIconData(0xf1d6);

  /// Warframe icons nightmare [IconData] with Unicode 0xf1d7
  static const IconData nightmare = WarframeIconData(0xf1d7);

  /// Warframe icons nightwave [IconData] with Unicode 0xf1d8
  static const IconData nightwave = WarframeIconData(0xf1d8);

  /// Warframe icons nightwavesDaily [IconData] with Unicode 0xf1d9
  static const IconData nightwavesDaily = WarframeIconData(0xf1d9);

  /// Warframe icons nightwavesElite [IconData] with Unicode 0xf1da
  static const IconData nightwavesElite = WarframeIconData(0xf1da);

  /// Warframe icons nightwavesWeekly [IconData] with Unicode 0xf1db
  static const IconData nightwavesWeekly = WarframeIconData(0xf1db);

  /// Warframe icons ostron [IconData] with Unicode 0xf1dc
  static const IconData ostron = WarframeIconData(0xf1dc);

  /// Warframe icons sigilsArbitersOfHexisArbitersLevel1 [IconData] with Unicode 0xf1dd
  static const IconData sigilsArbitersOfHexisArbitersLevel1 = WarframeIconData(0xf1dd);

  /// Warframe icons sigilsArbitersOfHexisArbitersLevel2 [IconData] with Unicode 0xf1de
  static const IconData sigilsArbitersOfHexisArbitersLevel2 = WarframeIconData(0xf1de);

  /// Warframe icons sigilsArbitersOfHexisArbitersLevel3 [IconData] with Unicode 0xf1df
  static const IconData sigilsArbitersOfHexisArbitersLevel3 = WarframeIconData(0xf1df);

  /// Warframe icons sigilsArbitersOfHexisArbitersLevel4 [IconData] with Unicode 0xf1e0
  static const IconData sigilsArbitersOfHexisArbitersLevel4 = WarframeIconData(0xf1e0);

  /// Warframe icons sigilsArbitersOfHexisArbitersLevel5 [IconData] with Unicode 0xf1e1
  static const IconData sigilsArbitersOfHexisArbitersLevel5 = WarframeIconData(0xf1e1);

  /// Warframe icons sigilsCephalonSudaCephalonSudaLevel1 [IconData] with Unicode 0xf1e2
  static const IconData sigilsCephalonSudaCephalonSudaLevel1 = WarframeIconData(0xf1e2);

  /// Warframe icons sigilsCephalonSudaCephalonSudaLevel2 [IconData] with Unicode 0xf1e3
  static const IconData sigilsCephalonSudaCephalonSudaLevel2 = WarframeIconData(0xf1e3);

  /// Warframe icons sigilsCephalonSudaCephalonSudaLevel3 [IconData] with Unicode 0xf1e4
  static const IconData sigilsCephalonSudaCephalonSudaLevel3 = WarframeIconData(0xf1e4);

  /// Warframe icons sigilsCephalonSudaCephalonSudaLevel4 [IconData] with Unicode 0xf1e5
  static const IconData sigilsCephalonSudaCephalonSudaLevel4 = WarframeIconData(0xf1e5);

  /// Warframe icons sigilsCephalonSudaCephalonSudaLevel5 [IconData] with Unicode 0xf1e6
  static const IconData sigilsCephalonSudaCephalonSudaLevel5 = WarframeIconData(0xf1e6);

  /// Warframe icons sigilsEntratiEntratiLevel1 [IconData] with Unicode 0xf1e7
  static const IconData sigilsEntratiEntratiLevel1 = WarframeIconData(0xf1e7);

  /// Warframe icons sigilsEntratiEntratiLevel2 [IconData] with Unicode 0xf1e8
  static const IconData sigilsEntratiEntratiLevel2 = WarframeIconData(0xf1e8);

  /// Warframe icons sigilsEntratiEntratiLevel3 [IconData] with Unicode 0xf1e9
  static const IconData sigilsEntratiEntratiLevel3 = WarframeIconData(0xf1e9);

  /// Warframe icons sigilsEntratiEntratiLevel4 [IconData] with Unicode 0xf1ea
  static const IconData sigilsEntratiEntratiLevel4 = WarframeIconData(0xf1ea);

  /// Warframe icons sigilsEntratiEntratiLevel5 [IconData] with Unicode 0xf1eb
  static const IconData sigilsEntratiEntratiLevel5 = WarframeIconData(0xf1eb);

  /// Warframe icons sigilsNecraloidNecraloidLevel1 [IconData] with Unicode 0xf1ec
  static const IconData sigilsNecraloidNecraloidLevel1 = WarframeIconData(0xf1ec);

  /// Warframe icons sigilsNecraloidNecraloidLevel2 [IconData] with Unicode 0xf1ed
  static const IconData sigilsNecraloidNecraloidLevel2 = WarframeIconData(0xf1ed);

  /// Warframe icons sigilsNecraloidNecraloidLevel3 [IconData] with Unicode 0xf1ee
  static const IconData sigilsNecraloidNecraloidLevel3 = WarframeIconData(0xf1ee);

  /// Warframe icons sigilsNegativeRank1 [IconData] with Unicode 0xf1ef
  static const IconData sigilsNegativeRank1 = WarframeIconData(0xf1ef);

  /// Warframe icons sigilsNegativeRank2 [IconData] with Unicode 0xf1f0
  static const IconData sigilsNegativeRank2 = WarframeIconData(0xf1f0);

  /// Warframe icons sigilsNeutral [IconData] with Unicode 0xf1f1
  static const IconData sigilsNeutral = WarframeIconData(0xf1f1);

  /// Warframe icons sigilsNewLokaNewLokaLevel1 [IconData] with Unicode 0xf1f2
  static const IconData sigilsNewLokaNewLokaLevel1 = WarframeIconData(0xf1f2);

  /// Warframe icons sigilsNewLokaNewLokaLevel2 [IconData] with Unicode 0xf1f3
  static const IconData sigilsNewLokaNewLokaLevel2 = WarframeIconData(0xf1f3);

  /// Warframe icons sigilsNewLokaNewLokaLevel3 [IconData] with Unicode 0xf1f4
  static const IconData sigilsNewLokaNewLokaLevel3 = WarframeIconData(0xf1f4);

  /// Warframe icons sigilsNewLokaNewLokaLevel4 [IconData] with Unicode 0xf1f5
  static const IconData sigilsNewLokaNewLokaLevel4 = WarframeIconData(0xf1f5);

  /// Warframe icons sigilsNewLokaNewLokaLevel5 [IconData] with Unicode 0xf1f6
  static const IconData sigilsNewLokaNewLokaLevel5 = WarframeIconData(0xf1f6);

  /// Warframe icons sigilsOstronOstronLevel1 [IconData] with Unicode 0xf1f7
  static const IconData sigilsOstronOstronLevel1 = WarframeIconData(0xf1f7);

  /// Warframe icons sigilsOstronOstronLevel2 [IconData] with Unicode 0xf1f8
  static const IconData sigilsOstronOstronLevel2 = WarframeIconData(0xf1f8);

  /// Warframe icons sigilsOstronOstronLevel3 [IconData] with Unicode 0xf1f9
  static const IconData sigilsOstronOstronLevel3 = WarframeIconData(0xf1f9);

  /// Warframe icons sigilsOstronOstronLevel4 [IconData] with Unicode 0xf1fa
  static const IconData sigilsOstronOstronLevel4 = WarframeIconData(0xf1fa);

  /// Warframe icons sigilsOstronOstronLevel5 [IconData] with Unicode 0xf1fb
  static const IconData sigilsOstronOstronLevel5 = WarframeIconData(0xf1fb);

  /// Warframe icons sigilsRedVeilRedVeilLevel1 [IconData] with Unicode 0xf1fc
  static const IconData sigilsRedVeilRedVeilLevel1 = WarframeIconData(0xf1fc);

  /// Warframe icons sigilsRedVeilRedVeilLevel2 [IconData] with Unicode 0xf1fd
  static const IconData sigilsRedVeilRedVeilLevel2 = WarframeIconData(0xf1fd);

  /// Warframe icons sigilsRedVeilRedVeilLevel3 [IconData] with Unicode 0xf1fe
  static const IconData sigilsRedVeilRedVeilLevel3 = WarframeIconData(0xf1fe);

  /// Warframe icons sigilsRedVeilRedVeilLevel4 [IconData] with Unicode 0xf1ff
  static const IconData sigilsRedVeilRedVeilLevel4 = WarframeIconData(0xf1ff);

  /// Warframe icons sigilsRedVeilRedVeilLevel5 [IconData] with Unicode 0xf200
  static const IconData sigilsRedVeilRedVeilLevel5 = WarframeIconData(0xf200);

  /// Warframe icons sigilsSolarisUnitedSolarisLevel1 [IconData] with Unicode 0xf201
  static const IconData sigilsSolarisUnitedSolarisLevel1 = WarframeIconData(0xf201);

  /// Warframe icons sigilsSolarisUnitedSolarisLevel2 [IconData] with Unicode 0xf202
  static const IconData sigilsSolarisUnitedSolarisLevel2 = WarframeIconData(0xf202);

  /// Warframe icons sigilsSolarisUnitedSolarisLevel3 [IconData] with Unicode 0xf203
  static const IconData sigilsSolarisUnitedSolarisLevel3 = WarframeIconData(0xf203);

  /// Warframe icons sigilsSolarisUnitedSolarisLevel4 [IconData] with Unicode 0xf204
  static const IconData sigilsSolarisUnitedSolarisLevel4 = WarframeIconData(0xf204);

  /// Warframe icons sigilsSolarisUnitedSolarisLevel5 [IconData] with Unicode 0xf205
  static const IconData sigilsSolarisUnitedSolarisLevel5 = WarframeIconData(0xf205);

  /// Warframe icons sigilsSteelMeridianSteelMeridianLevel1 [IconData] with Unicode 0xf206
  static const IconData sigilsSteelMeridianSteelMeridianLevel1 = WarframeIconData(0xf206);

  /// Warframe icons sigilsSteelMeridianSteelMeridianLevel2 [IconData] with Unicode 0xf207
  static const IconData sigilsSteelMeridianSteelMeridianLevel2 = WarframeIconData(0xf207);

  /// Warframe icons sigilsSteelMeridianSteelMeridianLevel3 [IconData] with Unicode 0xf208
  static const IconData sigilsSteelMeridianSteelMeridianLevel3 = WarframeIconData(0xf208);

  /// Warframe icons sigilsSteelMeridianSteelMeridianLevel4 [IconData] with Unicode 0xf209
  static const IconData sigilsSteelMeridianSteelMeridianLevel4 = WarframeIconData(0xf209);

  /// Warframe icons sigilsSteelMeridianSteelMeridianLevel5 [IconData] with Unicode 0xf20a
  static const IconData sigilsSteelMeridianSteelMeridianLevel5 = WarframeIconData(0xf20a);

  /// Warframe icons sigilsTheHoldfastsHoldfastsLevel1 [IconData] with Unicode 0xf20b
  static const IconData sigilsTheHoldfastsHoldfastsLevel1 = WarframeIconData(0xf20b);

  /// Warframe icons sigilsTheHoldfastsHoldfastsLevel2 [IconData] with Unicode 0xf20c
  static const IconData sigilsTheHoldfastsHoldfastsLevel2 = WarframeIconData(0xf20c);

  /// Warframe icons sigilsTheHoldfastsHoldfastsLevel3 [IconData] with Unicode 0xf20d
  static const IconData sigilsTheHoldfastsHoldfastsLevel3 = WarframeIconData(0xf20d);

  /// Warframe icons sigilsTheHoldfastsHoldfastsLevel4 [IconData] with Unicode 0xf20e
  static const IconData sigilsTheHoldfastsHoldfastsLevel4 = WarframeIconData(0xf20e);

  /// Warframe icons sigilsTheHoldfastsHoldfastsLevel5 [IconData] with Unicode 0xf20f
  static const IconData sigilsTheHoldfastsHoldfastsLevel5 = WarframeIconData(0xf20f);

  /// Warframe icons sigilsThePerrinSequencePerrinLevel1 [IconData] with Unicode 0xf210
  static const IconData sigilsThePerrinSequencePerrinLevel1 = WarframeIconData(0xf210);

  /// Warframe icons sigilsThePerrinSequencePerrinLevel2 [IconData] with Unicode 0xf211
  static const IconData sigilsThePerrinSequencePerrinLevel2 = WarframeIconData(0xf211);

  /// Warframe icons sigilsThePerrinSequencePerrinLevel3 [IconData] with Unicode 0xf212
  static const IconData sigilsThePerrinSequencePerrinLevel3 = WarframeIconData(0xf212);

  /// Warframe icons sigilsThePerrinSequencePerrinLevel4 [IconData] with Unicode 0xf213
  static const IconData sigilsThePerrinSequencePerrinLevel4 = WarframeIconData(0xf213);

  /// Warframe icons sigilsThePerrinSequencePerrinLevel5 [IconData] with Unicode 0xf214
  static const IconData sigilsThePerrinSequencePerrinLevel5 = WarframeIconData(0xf214);

  /// Warframe icons sigilsTheQuillsQuillsLevel1 [IconData] with Unicode 0xf215
  static const IconData sigilsTheQuillsQuillsLevel1 = WarframeIconData(0xf215);

  /// Warframe icons sigilsTheQuillsQuillsLevel2 [IconData] with Unicode 0xf216
  static const IconData sigilsTheQuillsQuillsLevel2 = WarframeIconData(0xf216);

  /// Warframe icons sigilsTheQuillsQuillsLevel3 [IconData] with Unicode 0xf217
  static const IconData sigilsTheQuillsQuillsLevel3 = WarframeIconData(0xf217);

  /// Warframe icons sigilsTheQuillsQuillsLevel4 [IconData] with Unicode 0xf218
  static const IconData sigilsTheQuillsQuillsLevel4 = WarframeIconData(0xf218);

  /// Warframe icons sigilsTheQuillsQuillsLevel5 [IconData] with Unicode 0xf219
  static const IconData sigilsTheQuillsQuillsLevel5 = WarframeIconData(0xf219);

  /// Warframe icons sigilsVentKidsVentKidsLevel1 [IconData] with Unicode 0xf21a
  static const IconData sigilsVentKidsVentKidsLevel1 = WarframeIconData(0xf21a);

  /// Warframe icons sigilsVentKidsVentKidsLevel2 [IconData] with Unicode 0xf21b
  static const IconData sigilsVentKidsVentKidsLevel2 = WarframeIconData(0xf21b);

  /// Warframe icons sigilsVentKidsVentKidsLevel3 [IconData] with Unicode 0xf21c
  static const IconData sigilsVentKidsVentKidsLevel3 = WarframeIconData(0xf21c);

  /// Warframe icons sigilsVentKidsVentKidsLevel4 [IconData] with Unicode 0xf21d
  static const IconData sigilsVentKidsVentKidsLevel4 = WarframeIconData(0xf21d);

  /// Warframe icons sigilsVentKidsVentKidsLevel5 [IconData] with Unicode 0xf21e
  static const IconData sigilsVentKidsVentKidsLevel5 = WarframeIconData(0xf21e);

  /// Warframe icons sigilsVoxSolarisVoxLevel1 [IconData] with Unicode 0xf21f
  static const IconData sigilsVoxSolarisVoxLevel1 = WarframeIconData(0xf21f);

  /// Warframe icons sigilsVoxSolarisVoxLevel2 [IconData] with Unicode 0xf220
  static const IconData sigilsVoxSolarisVoxLevel2 = WarframeIconData(0xf220);

  /// Warframe icons sigilsVoxSolarisVoxLevel3 [IconData] with Unicode 0xf221
  static const IconData sigilsVoxSolarisVoxLevel3 = WarframeIconData(0xf221);

  /// Warframe icons sigilsVoxSolarisVoxLevel4 [IconData] with Unicode 0xf222
  static const IconData sigilsVoxSolarisVoxLevel4 = WarframeIconData(0xf222);

  /// Warframe icons sigilsVoxSolarisVoxLevel5 [IconData] with Unicode 0xf223
  static const IconData sigilsVoxSolarisVoxLevel5 = WarframeIconData(0xf223);

  /// Warframe icons simaris [IconData] with Unicode 0xf224
  static const IconData simaris = WarframeIconData(0xf224);

  /// Warframe icons solaris [IconData] with Unicode 0xf225
  static const IconData solaris = WarframeIconData(0xf225);

  /// Warframe icons spLogo [IconData] with Unicode 0xf226
  static const IconData spLogo = WarframeIconData(0xf226);

  /// Warframe icons standing [IconData] with Unicode 0xf227
  static const IconData standing = WarframeIconData(0xf227);

  /// Warframe icons theHex [IconData] with Unicode 0xf228
  static const IconData theHex = WarframeIconData(0xf228);

  /// Warframe icons wfcd [IconData] with Unicode 0xf229
  static const IconData wfcd = WarframeIconData(0xf229);
}
